/**
 * Live Claude provider check — run with: npm run smoke:claude
 *
 * Requires ANTHROPIC_API_KEY. Makes real API calls (a handful of requests).
 * Verifies the structured-output path end to end: generation, review, and
 * refinement, plus that operations Claude proposes actually validate.
 */

import { ClaudeProvider } from '@/lib/ai/claude-provider'
import { allQuestions } from '@/lib/survey/helpers'

const p = new ClaudeProvider()
let failures = 0
const check = (label: string, ok: boolean, detail = '') => {
  if (!ok) failures += 1
  console.log(
    `  ${ok ? 'PASS' : 'FAIL'}  ${label}${detail ? ` — ${detail}` : ''}`
  )
}

console.log('\nClaude generateSurvey')
const gen = await p.generateSurvey({
  objective:
    'Create a post-purchase customer experience survey. Measure satisfaction, delivery experience, product quality, customer support and likelihood to recommend. Keep it under 5 minutes.'
})
if (!gen.ok) {
  console.log(`  FAIL  ${gen.error.code}: ${gen.error.message}`)
  process.exit(1)
}
const s = gen.data.survey
const n = allQuestions(s).length
console.log(
  `  "${s.title}" — ${s.sections.length} sections, ${n} questions, ~${s.meta.estimatedMinutes} min`
)
check('has sections', s.sections.length >= 3)
check('has questions', n >= 6)
check(
  'all questions have text',
  allQuestions(s).every(q => q.question.text.length > 3)
)
check('respects 5-min budget', (s.meta.estimatedMinutes ?? 99) <= 7)
check('marked generated by claude', s.meta.generatedBy === 'claude')
check(
  'has an NPS question',
  allQuestions(s).some(q => q.question.type === 'nps')
)
for (const { question } of allQuestions(s).slice(0, 4)) {
  console.log(`    [${question.type}] ${question.text}`)
}

console.log('\nClaude reviewSurvey')
const rev = await p.reviewSurvey({ survey: s })
if (!rev.ok) {
  check(
    'reviewSurvey succeeds',
    false,
    `${rev.error.code}: ${rev.error.message}`
  )
} else {
  const { health, issues } = rev.data.review
  console.log(
    `  health ${health.score}/100 (${health.grade}) — ${health.summary}`
  )
  for (const i of issues) console.log(`    [${i.severity}] ${i.message}`)
  check('score in range', health.score >= 0 && health.score <= 100)
  check('checks are consistent', health.checksPassed <= health.checksTotal)
  const anchored = issues.filter(i => i.questionId)
  const valid = new Set(allQuestions(s).map(q => q.question.id))
  check(
    'every anchored issue points at a real question',
    anchored.every(i => valid.has(i.questionId!))
  )
}

console.log('\nClaude refineSurvey — natural language')
const ref = await p.refineSurvey({
  survey: s,
  instruction:
    'If someone gives a rating below 3, ask why they were dissatisfied.'
})
if (!ref.ok) {
  check(
    'refineSurvey (logic) succeeds',
    false,
    `${ref.error.code}: ${ref.error.message}`
  )
} else {
  console.log(`  changes: ${ref.data.changes.join(' | ')}`)
  check(
    'added a logic rule',
    ref.data.survey.logic.length > s.logic.length,
    `logic ${s.logic.length} -> ${ref.data.survey.logic.length}`
  )
  check('added a follow-up question', allQuestions(ref.data.survey).length > n)
  const rejected = (ref.data.operations ?? []).filter(o => !o.applied)
  check(
    'no operations rejected',
    rejected.length === 0,
    rejected.map(r => r.detail).join('; ')
  )
}

console.log('\nClaude refineSurvey — shorten')
const short = await p.refineSurvey({
  survey: s,
  instruction: 'Make this survey shorter.'
})
if (short.ok) {
  console.log(`  changes: ${short.data.changes.slice(0, 3).join(' | ')}`)
  check('removed questions', allQuestions(short.data.survey).length < n)
} else {
  check('refineSurvey (shorten) succeeds', false, short.error.message)
}

console.log(
  failures === 0
    ? '\nAll Claude checks passed.\n'
    : `\n${failures} check(s) failed.\n`
)
process.exit(failures === 0 ? 0 : 1)
